# Generated by Django 6.0 on 2026-01-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AWD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='offering',
            name='duration',
            field=models.CharField(default='Self-paced', max_length=50),
        ),
        migrations.AddField(
            model_name='offering',
            name='enrolled',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offering',
            name='instructor',
            field=models.CharField(default='Staff', max_length=255),
        ),
    ]
